config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "packages#index"

  resources :packages, only: %i[index show new create] do
    collection do
      resources :validations, only: %i[create], module: :packages, as: :package_validations
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="bg-red-lightest border-l-4 border-red text-red-dark m-4 p-4">
    <p class="font-bold pb-2"><%= local_assigns.fetch :title, 'Error(s) found' %>:</p>
    <% object.errors.full_messages.each do |error_message| %>
      <p class="pl-6">- <%= error_message %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <%= tag.div class: "#{flash_class(type)} border-l-4 p-4 flex items-center",
    data: { controller: 'removable' } do %>
    <p class="flex-1"><%= message %></p>
    <div class="icon-link hover:cursor-pointer flex items-center">
      <span data-action="click->removable#remove" data-feather="x"></span>
    </div>
  <% end %>
<% end %>

app/views/shared/_sidebar.html.erb
<nav class="flex flex-col sm:h-full">
  <%= link_to root_path, class: 'self-center p-4 w-3/4 sm:w-full' do %>
    <%= image_tag 'text_logo.svg' %>
  <% end %>

  <div class="px-4 py-4 hidden sm:flex">
    <%= image_tag 'slogan.svg' %>
  </div>

  <div class="flex-1 self-stretch"></div>

  <% unless current_page? new_package_path %>
    <div class="hidden self-center sm:flex">
      <%= link_to new_package_path, class: 'link-with-icon text-grey-dark hover:text-grey-darker pb-2' do %>
        <span data-feather="plus"></span>
        <span>Submit a Package</span>
      <% end %>
    </div>
  <% end %>

  <%= link_to 'https://gitlab.com/stim-awesome/stim-awesome',
    target: '_blank',
    class: 'hidden sm:flex p-3 justify-center no-underline text-grey-darkest border-t hover:bg-smoke-lightest' do %>
    <div class="h-12 w-12 pr-2" data-feather="gitlab"></div>
    <div class="flex flex-col h-full font-logo">
      <h3 class="flex-1 text-center">Contribute to</h3>
      <h3 class="flex-1 text-center">StimAwesome</h3>
    </div>
  <% end %>
</nav>